apiVersion: apps/v1 
kind: Deployment
metadata:
  name: comingsoon-page-img-deployment 
  namespace: comingsoon1
spec:
  selector:
    matchLabels:
      app: comingsoon-page
  replicas: 1
  template:
    metadata:
      labels:
        app: comingsoon-page
    spec:
      containers:
      - name: comingsoon-page
        image: portainer/agent
        ports:
        - containerPort: 80
